---
- name: install mysql
  apt: pkg=mysql-server-5.6 state=installed update-cache=yes

- name: install mysql confs
  copy: src={% templatetag openvariable %} item {% templatetag closevariable %} dest=/etc/mysql/conf.d/{% templatetag openvariable %} item {% templatetag closevariable %}
  with_items:
    - utf8_innodb.cnf
    - slow_query.cnf
    - transaction.cnf
    - bind_address.cnf
    - packet_size.cnf
    - buffer_pool_size.cnf
  notify:
    - reload mysql
    - restart mysql

- name: create project database
  mysql_db: name={% templatetag openvariable %} project_name {% templatetag closevariable %} collation=utf8_general_ci encoding=utf8 state=present

- name: set connect from anywhere privileges
  mysql_user: name=root password= priv=*.*:ALL host=% append_privs=yes

- name: install mysql auto backup
  apt: pkg={% templatetag openvariable %} item {% templatetag closevariable %} state=installed update-cache=yes
  with_items:
    - mysql-client
    - automysqlbackup
