---
- name: install mysql
  apt: pkg=mysql-server-5.6 state=installed update-cache=yes

- name: install mysql confs
  copy: src={{ item }} dest=/etc/mysql/conf.d/{{ item }}
  with_items:
    - utf8_innodb.cnf
    - slow_query.cnf
    - transaction.cnf
    - bind_address.cnf
    - packet_size.cnf
    - buffer_pool_size.cnf
  notify:
    - reload mysql
    - restart mysql

- name: create project database
  mysql_db: name={{ project_name }} collation=utf8_general_ci encoding=utf8 state=present

- name: set connect from anywhere privileges
  mysql_user: name=root password= priv=*.*:ALL host=% append_privs=yes
