---
- name: install mysql
  apt: pkg=mysql-server-5.6 state=installed update-cache=yes

- name: touch mysqld conf
  copy: src=mysqld.cnf dest=/etc/mysql/conf.d/mysqld.cnf

- name: set mysql conf
  lineinfile: "dest=/etc/mysql/conf.d/mysqld.cnf regexp='^{{ item.name }} .*' line='{{ item.name }} = {{ item.value }}'"
  with_items: "{{ mysqld_vars|default([]) }}"
  notify:
    - reload mysql
    - restart mysql

- name: create project database
  mysql_db: name={{ project_name }} collation=utf8_general_ci encoding=utf8 state=present

- name: set connect from anywhere privileges
  mysql_user: name=root password= priv=*.*:ALL host=% append_privs=yes
