---
- name: install supervisor
  apt: pkg=supervisor state=installed update-cache=yes

- name: install supervisord conf
  copy: src=supervisord.conf dest=/etc/supervisor/supervisord.conf
  notify: reload supervisor
