---
- name: install system packages
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - build-essential
    - gcc
    - git
    - libevent-dev
    - libxml2-dev
    - libxslt1-dev
    - libpq-dev
    - libncurses5-dev
    - libmysqlclient15-dev
    - libjpeg-dev
    - python-dev
    - python-setuptools
    - python-software-properties
    - python-mysqldb

- name: install python packages
  easy_install: name={{ item }}
  with_items:
    - pip
    - virtualenv

- name: create project directory
  file: state={{ item.state }} path={{ item.path }}
  with_items:
    - { path: "{{ project_root }}", state: directory }
    - { path: "{{ project_src }}" , state: directory }
    - { path: "{{ project_venv }}", state: directory }

- name: create project user
  user: home={{ project_root }}/home/ name={{ project_user }} shell=/bin/bash state=present

- name: install authorized keys
  authorized_key:
    user={{ project_user }}
    key="{{lookup('pipe', 'curl -s https://github.com/' + item + '.keys')}}"
  with_items: authorized_github_users

- name: give project user supervisorctl sudo perm
  lineinfile: "dest=/etc/sudoers state=present regexp='^{{ project_user }}' line='{{ project_user }} ALL=(ALL) NOPASSWD:/usr/bin/supervisorctl'"

- name: update project directory perms
  file: owner={{ project_user }} group={{ project_user }} path={{ project_root }} state=directory recurse=yes
