---
- name: configure rsyslog to send to papertrail
  lineinfile: "dest=/etc/rsyslog.conf regexp='.*papertrail.*' line='*.*  @{% templatetag openvariable %} papertrail_host {% templatetag closevariable %}
  notify: restart rsyslog
