- name: create gunicorn logging directory
  file: state=directory path=/var/log/gunicorn

- name: install gunicorn supervisor conf
  template: src=supervisor-gunicorn.conf dest=/etc/supervisor/conf.d/{{ project_name }}.gunicorn.conf
  notify: reload supervisor
