---
- name: restart celeryd
  supervisorctl: name={{ project_name }}_celeryd state=restarted
  sudo: yes

- name: restart celerybeat
  supervisorctl: name={{ project_name }}_celerybeat state=restarted
  sudo: yes
