---
- name: set timezone
  copy: content={{ timezone }} dest=/etc/timezone owner=root group=root mode=0644
  notify:
    - update timezone

- name: install system packages
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
    - build-essential
    - gcc
    - vim
    - tmux
    - curl
    - locate
    - htop
    - ufw
    - ntp

- name: configure firewall
  ufw: rule={{ item.rule }} port={{ item.port }} from={{ item.from|default("0.0.0.0/0") }}
  with_items: ufw_rules

- name: enable firewall
  ufw: logging=on policy=deny state=enabled

- name: run ntpd server
  service: name=ntp state=running enabled=yes
